global:
  g_pGameRules:
    windows: [ 0x85, 0xc0, 0x74, 0x3f, 0x50, 0xe8, 0x3f, 0x3f, 0x3f, 0x3f, 0x83, 0xc4, 0x04, 0x56, 0xe8, 0x3f, 0x3f, 0x3f, 0x3f, 0xa3 ]
    linux: g_pGameRules
    var: true
CBaseEntity:
  SUB_Remove:
    linux: _ZN11CBaseEntity10SUB_RemoveEv
    windows: ?SUB_Remove@CBaseEntity@@QAEXXZ
CBasePlayerItem:
  DestroyItem:
    linux: _ZN15CBasePlayerItem11DestroyItemEv
    windows: ?DestroyItem@CBasePlayerItem@@QAEXXZ
  DefaultTouch:
    linux: _ZN15CBasePlayerItem12DefaultTouchEP11CBaseEntity
    windows: ?DefaultTouch@CBasePlayerItem@@QAEXPAVCBaseEntity@@@Z
  FallThink:
    linux: _ZN15CBasePlayerItem9FallThinkEv
    windows: ?FallThink@CBasePlayerItem@@QAEXXZ
  Materialize:
    linux: _ZN15CBasePlayerItem11MaterializeEv
    windows: ?Materialize@CBasePlayerItem@@QAEXXZ
  AttemptToMaterialize:
    linux: _ZN15CBasePlayerItem20AttemptToMaterializeEv
    windows: ?AttemptToMaterialize@CBasePlayerItem@@QAEXXZ
CBasePlayer:
  GiveNamedItem:
    linux: _ZN11CBasePlayer13GiveNamedItemEPKc
    windows: [ 0x8b, 0x3f, 0x3f, 0x04, 0x56, 0x57, 0x8b, 0x3f, 0x8b, 0x3f, 0x3f, 0x3f, 0x3f, 0x3f, 0x2b, 0x3f, 0x98, 0x3f, 0x3f, 0x3f ]
  HasNamedPlayerItem:
    linux: _ZN11CBasePlayer18HasNamedPlayerItemEPKc
    windows: [ 0x83, 0xec, 0x08, 0x8b, 0x3f, 0x3f, 0x3f, 0x53, 0x81, 0xc1, 0xb4, 0x04, 0x3f, 0x3f ]
  PackDeadPlayerItems:
    linux: _ZN11CBasePlayer19PackDeadPlayerItemsEv
    windows: [ 0x81, 0xec, 0x3f, 0x3f, 0x3f, 0x3f, 0x53, 0x55, 0x56, 0x57, 0x8b, 0xd9 ]
  IsOnLadder:
    linux: _ZN11CBasePlayer10IsOnLadderEv
    windows: [ 0x8b, 0x41, 0x04, 0x33, 0xc9, 0x83, 0x3f, 0x08, 0x01, 0x3f, 0x3f, 0x05, 0x0f, 0x3f, 0x3f, 0x8b, 0x3f, 0xc3 ]
  FlashlightIsOn:
    linux: _ZN11CBasePlayer14FlashlightIsOnEv
    windows: [ 0x8b, 0x41, 0x04, 0x8b, 0x80, 0x18, 0x01, 0x3f, 0x3f, 0x83 ]
  FlashlightTurnOn:
    linux: _ZN11CBasePlayer16FlashlightTurnOnEv
    windows: [ 0x56, 0x8b, 0xf1, 0x8b, 0x3f, 0x3f, 0x3f, 0x3f, 0x3f, 0x8b, 0x3f, 0xff, 0x3f, 0x0c ]
  FlashlightTurnOff:
    linux: _ZN11CBasePlayer17FlashlightTurnOffEv
    windows: [ 0x56, 0x8b, 0xf1, 0x6a, 0x3f, 0x6a, 0x3f, 0x8b, 0x3f, 0x04, 0x68, 0xcd, 0xcc, 0x4c, 0x3f, 0x68, 0x3f, 0x3f, 0x80, 0x3f, 0x68, 0x3f, 0x3f, 0x3f, 0x3f, 0x8b, 0x3f, 0x08, 0x02, 0x3f, 0x3f, 0x6a, 0x3f, 0x51, 0xe8, 0x3f, 0x3f, 0x3f, 0x3f, 0x8b, 0x3f, 0x04, 0x8b, 0x3f, 0x18, 0x01, 0x3f, 0x3f ]
  DropPlayerItem:
    linux: _ZN11CBasePlayer14DropPlayerItemEPc
    windows: [ 0x83, 0xec, 0x38, 0x53, 0x8b, 0xd9, 0x8b, 0x0d, 0x3f, 0x3f, 0x3f, 0x3f, 0x55 ]
    mask: 0x3f
CBasePlayerAmmo:
  DefaultTouch:
    linux: _ZN15CBasePlayerAmmo12DefaultTouchEP11CBaseEntity
    windows: ?DefaultTouch@CBasePlayerAmmo@@QAEXPAVCBaseEntity
  Materialize:
    linux: _ZN15CBasePlayerAmmo11MaterializeEv
    windows: ?Materialize@CBasePlayerAmmo@@QAEXXZ
